# 一致收敛积分的分析性质

现在讨论含参变量反常积分的分析性质，即连续性、可微性和可导性。

设反常积分 $\displaystyle \int_{a}^{+\infty} f(x,y) \, dx$ 对于每个 $\displaystyle y \in [c,d]$ 都收敛，这样就定义了函数
$$
I(y) = \int_{a}^{+\infty} f(x,y) \, dx,   y \in [c,d]
$$

任取一列严格单调增加的数列 $\displaystyle {a_n}$ , 它满足 $\displaystyle a_0 = a$ 以及 $\displaystyle a_n \to +\infty(n \to \infty)$.置
$$
u_n(y) = \int_{a_{n-1}}^{a_n}f(x,y) \, dx, n=1,2,...
$$

那么
$$
\int_{a}^{+\infty}f(x,y) \, dx = \sum_{n=1}^{\infty}\int_{a_{n-1}}^{a_n}f(x,y) \, dx = \sum_{n=1}^{\infty} u_n(y).
$$

在以下引理的叙述和定理的证明中我们仍采用上面的记号。

利用 Cauchy 收敛原理容易证明如下的引理：

::: {#lem-Cauchy}

若含参变量反常积分 $\displaystyle \int_{a}^{+\infty}f(x,y) \, dx$ 关于 $\displaystyle y$ 在 $\displaystyle [c,d]$ 上一致收敛，则函数项级数 $\displaystyle \sum_{n=1}^{\infty} u_n(y)$ 在 $\displaystyle [c,d]$ 上一致收敛。

:::

::: {#thm-consistent}

## 连续性定理
设 $\displaystyle f(x,y)$ 在 $\displaystyle [a,+\infty) \times [c,d]$ 上连续， $\displaystyle \int_{a}^{+\infty}f(x,y) \, dx$ 关于 $\displaystyle y$ 在 $\displaystyle [c,d]$ 上一致收敛，则函数

$$
I(y) = \int_{a}^{+\infty}f(x,y)\, dx
$$

在 $\displaystyle [c,d]$ 上连续，即

$$
\lim_{y \to y_0} \int_{a}^{+\infty}f(x,y)dx = \int_{a}^{+\infty}\lim_{y \to y_0}f(x,y) \, dx, \qquad  y_0 \in [c,d]
$$

也就是说，极限运算与积分运算可以交换。

:::

::: {.proof}
## @thm-consistent[连续性定理]
因为 $\displaystyle \int_{a}^{+\infty}f(x,y) \, dx$ 在 $\displaystyle [c,d]$ 上一致收敛，那么由 @lem-Cauchy 知 $\displaystyle \sum_{n=1}^{\infty} u_n(y)$ 在 $\displaystyle [c,d]$
上一致收敛。由于 $\displaystyle f(x,y)$ 在 $\displaystyle [a_{n-1},a_{n}] \times [c,d]$ 上连续，
那么由常义含参变量积分的连续性定理知

$$
u_{n}(y)=\int_{a_{n-1}}^{a_{n}}f(x,y)\,dx
$$

连续 $\displaystyle (n=1,2,...)$. 根据一致连续收敛级数的性质就知道和函数

$$
I(y) = \int_{a}^{+\infty} f(x,y)dx = \sum_{n=1}^{\infty}u_{n}(y)
$$

连续。

:::

注意，Dini定理并不是这个定理的逆定理。Dini 定理只说明了在 $\displaystyle f(x,y)$ 保持定号
的情况下，由 $\displaystyle I(y)=\int_{a}^{+\infty}f(x,y)\,dx$ 的连续性可以推出 $\displaystyle \int_{a}^{+\infty}f(x,y)dx$
的一致收敛性。读者可以举例说明：去掉“保持定号”条件可能导致结论不成立。

::: {#thm-积分次序交换定理}

# 积分次序交换定理

设 $\displaystyle f(x,y)$ 在 $\displaystyle [a,+\infty] \times [c,d]$ 上连续，
$\displaystyle \int_{a}^{+\infty}f(x,y)dx$ 关于 $\displaystyle y$ 在 $\displaystyle [c,d]$
上一致收敛，则

$$
\int_{c}^{d}dy\int_{a}^{+\infty}f(x,y)dx = \int_{a}^{+\infty}dx\int_{c}^{d}f(x,y)dy,
$$

即积分次序可交换.
:::

::: {.proof}

由 @lem-Cauchy 知 $\displaystyle \sum_{n=1}^{\infty}u_{n}(y)$ 在 $\displaystyle [c,d]$ 
上一致收敛。根据一致收敛级数的和号与积分号可以交换的结论得

\begin{align}

\int_{c}^{d}dy\int_{a}^{+\infty}f(x,y)dx &= \int_{c}^{d}(\sum_{n=1}^{\infty}u_{n}(y))dy=\sum_{n=1}^{\infty}\int_{c}^{d}u_{n}(y)dy \\
&= \sum_{n=1}^{\infty}\int_{c}^{d}(\int_{a_{n-1}}^{a_{n}}f(x,y)dx)dy = \sum_{n=1}^{\infty}\int_{c}^{d}dy\int_{a_{n-1}}^{a_{n}}f(x,y)dx \\
&= \sum_{n=1}^{\infty}\int_{a_{n-1}}^{a_{n}}dx\int_{c}^{d}f(x,y)dy = \int_{a}^{+\infty}dx\int_{c}^{d}f(x,y)dy.

\end{align}

其中第二行到第三行的推到利用了常义含参变量积分的积分次序可交换定理.
:::

当 $\displaystyle [c,d]$ 也改为无穷区间 $\displaystyle [c,+\infty)$ 时，本定理的条件就不足以保证积分次序可交换，但有下面的结论：

::: {#thm-积分次序交换定理2}

# 积分次序交换定理2

设 $\displaystyle f(x,y)$ 在 $\displaystyle [a,+\infty) \times [c,+\infty)$ 上连续，且 $\displaystyle \int_{a}^{+\infty}f(x,y)dx$
关于 $\displaystyle y$ 在 $\displaystyle [c,C]$ 上一致收敛 $\displaystyle (c<C<+\infty)$ ， $\displaystyle \int_{c}^{+\infty}f(x,y)dy$
关于 $\displaystyle x$ 在 $\displaystyle [a,A]$ 上一致收敛 $\displaystyle (a<A<+\infty)$.
进一步假设 $\displaystyle \int_{a}^{+\infty}dx\int_{c}^{+\infty} \left| f(x,y) \right | dy$ 和 $\displaystyle \int_{c}^{+\infty}dy \int_{a}^{+\infty} \left| f(x,y) \right | dx$
中有一个存在，那么

$$
\int_{c}^{+\infty}dy\int_{a}^{+\infty}f(x,y)dx = \int_{a}^{+\infty}dx\int_{c}^{+\infty}f(x,y)dy.
$$

这个定理的证明较为复杂，这里从略。
:::


::: {#thm-积分号下求导定理}

# 积分号下求导定理
设 $\displaystyle f(x,y),f_{y}(x,y)$ 都在 $\displaystyle [a,+\infty) \times [c,d]$
上连续，且 $\displaystyle \int_{a}^{+\infty}f(x,y)dx$ 对于每个 $\displaystyle y \in [c,d]$ 收敛。进一步假设 $\displaystyle \int_{a}^{+\infty}f_{y}(x,y)dx$ 关于 $\displaystyle y$ 在 $\displaystyle [c,d]$ 上一致收敛。则 $\displaystyle I(y)=\int_{a}^{+\infty}f(x,y)dx$ 在 $\displaystyle [c,d]$ 上可导，并且在 $\displaystyle [c,d]$ 上成立

$$
I'(y) = \int_{a}^{+\infty}f_{y}(x,y)dx,
$$

即

$$
\frac{d}{dy}\int_{a}^{+\infty}f(x,y)dx = \int_{a}^{+\infty}\frac{\partial}{\partial y}f(x,y)dx,
$$

也就是说，求导运算与积分运算可交换。

:::

::: {.proof}

记 $\displaystyle \varphi(y) = \int_{a}^{+\infty}f_{y}(x,y)dx$, 由 $\displaystyle \int_{a}^{+\infty}f_{y}(x,y)dx$ 在 $\displaystyle [c,d]$ 上一致收敛的假设知 $\displaystyle \varphi(y)$ 在 $\displaystyle [c,d]$ 上连续。于是对于 $\displaystyle y \in [c,d]$, 由 @thm-积分次序交换定理 得

\begin{align}
\int_{c}^{y}\varphi(z)dz &= \int_{c}^{y}dz\int_{a}^{+\infty}f_{z}(x,z)dx = \int_{a}^{+\infty}dx\int_{c}^{y}f_{z}(x,z)dz \\
&= \int_{a}^{+\infty}[f(x,y)-f(x,c)]dx = \int_{a}^{+\infty}f(x,y)dx - \int_{a}^{+\infty}f(x,c)dx \\
&= I(y) - I(c).
\end{align}

由于 $\displaystyle \varphi(y)$ 在 $\displaystyle [c,d]$ 上连续，所以函数 $\displaystyle \int_{c}^{y}\varphi(z)dz$ 可导，从而 $\displaystyle I(y)$ 可导。两边求导就得

$$
I'(y) = \varphi(y) = \int_{a}^{+\infty}f_{y}(x,y)dx.
$$

:::

::: {.callout-warning}
如果把含参变量反常积分看成是一个**函数**的话，那么 @thm-积分号下求导定理 告诉我们其导数也是一个含参变量反常积分。
:::