project:
  type: website
  output-dir: docs

website:
  title: "Calculus"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: Euler积分
      - 1.qmd
  sidebar: 
    style: "docked"
    search: true
    contents:
      - section: "含参变量积分"
        contents:
          - 1.qmd
          - about.qmd
  
format:
  html:
    theme:
      - Minty
      - brand
    css: styles.css
    toc: true



