project:
  type: website
  output-dir: docs

website:
  title: "Calculus"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - 1.qmd
  sidebar: 
    style: "docked"
    search: true
    contents:
      - test: "含参变量积分"
        href: 1.qmd

format:
  html:
    theme:
      - Minty
      - brand
    css: styles.css
    toc: true



